### ISSUE TITLE
Link is not working for VRX simulator

### ISSUE THREAD

**Issue by Subhamtt19** [EdytaKal/ROS-based-simulator-autonomous-sailboat#4]
To install the Virtual RobotX Simulator follow the instructions from the following website: https://bitbucket.org/osrf/vrx/wiki/tutorials/SystemSetupInstall

Please update the link

**Comment by EdytaKal** [comment]
I have updated the link. It looks like the code/instructions for the VRX installations have been moved over to GitHub. Hope that helps.
